Carlos1408/MovieCorp

- backend/src/app.js
- backend/src/index.js
Servidor backend basico creado, apto para funcionamiento
> funcionamiento basico de backend implementado cc

- backend/src/app.js
- backend/src/controllers/users.controller.js
- backend/src/index.js
- backend/src/libs/mongoose.js
- backend/src/models/user.js
- backend/src/routes/users.routes.js
Rutas con endpoints, funciones de controlador y modelo de usuario creado para api, falta testing
> rutas, controladores y modelo creados para users cc

- frontend/src/app/modules/admin/admin-routing.module.ts
- frontend/src/app/modules/admin/admin.module.ts
- frontend/src/app/modules/admin/pages/cinemas/cinemas.component.html
- frontend/src/app/modules/admin/pages/cinemas/cinemas.component.ts
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-form/cinema-form.component.html
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-form/cinema-form.component.ts
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-table/cinema-table.component.html
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-table/cinema-table.component.ts
> H14 gui-crud cines vc

- frontend/src/app/modules/admin/admin-routing.module.ts
- frontend/src/app/modules/admin/admin.module.ts
- frontend/src/app/modules/admin/pages/rooms/components/room-form/room-form.component.html
- frontend/src/app/modules/admin/pages/rooms/components/room-form/room-form.component.ts
- frontend/src/app/modules/admin/pages/rooms/components/room-table/room-table.component.html
- frontend/src/app/modules/admin/pages/rooms/components/room-table/room-table.component.ts
- frontend/src/app/modules/admin/pages/rooms/rooms.component.html
- frontend/src/app/modules/admin/pages/rooms/rooms.component.ts
Creacion de GUI Y CRUD de salas
> H17 GUi-CRUD-SALAS vc

- .gitignore
- backend/package-lock.json
- backend/package.json
- backend/src/controllers/users.controller.js
update user actualizado, encriptado de password agregado
> encriptacion de password y update de user actualizados cc

- frontend/src/app/app.module.ts
- frontend/src/app/modules/management/pages/users/components/user-form/user-form.component.html
- frontend/src/app/modules/management/pages/users/components/user-form/user-form.component.ts
- frontend/src/app/modules/management/pages/users/components/user-table/user-table.component.ts
- frontend/src/app/modules/management/pages/users/users.component.html
- frontend/src/app/modules/management/pages/users/users.component.ts
- frontend/src/environments/environment.ts
Registro de usuario funcionando
> metodo de registro de usuario creado usando servicio cc

- frontend/angular.json
- frontend/package.json
- frontend/src/app/app.component.ts
- frontend/src/app/app.module.ts
- frontend/src/app/primeng.module.ts
- frontend/src/styles.scss
Migracion de framework de bootstrap a primeng
> primeng migracion de aplicacion cc

- frontend/src/app/primeng.module.ts
- frontend/src/app/shared/components/navbar/navbar.component.html
Migracion de navbar a menubar de primeng
> navbar migrada a primeng menubar cc

- frontend/src/app/modules/management/pages/users/components/user-form/user-form.component.ts
- frontend/src/app/modules/management/pages/users/components/user-table/user-table.component.html
- frontend/src/app/modules/management/pages/users/components/user-table/user-table.component.ts
- frontend/src/app/modules/management/pages/users/users.component.html
- frontend/src/app/modules/management/pages/users/users.component.ts
- frontend/src/app/shared/services/user.service.ts
edicion de datos de usuario con formulario implementado
> edicion de usuario agregada cc

- frontend/src/app/modules/admin/pages/cinemas/cinemas.component.html
- frontend/src/app/modules/admin/pages/cinemas/cinemas.component.ts
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-form/cinema-form.component.ts
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-table/cinema-table.component.html
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-table/cinema-table.component.ts
- frontend/src/app/shared/services/cinema.service.ts
> HU15/edicion de datos de cine VC

- backend/src/app.js
- backend/src/controllers/rooms.controller.js
- backend/src/models/room.js
- backend/src/routes/rooms.routes.js
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-form/cinema-form.component.ts
- frontend/src/app/modules/admin/pages/rooms/components/room-form/room-form.component.html
- frontend/src/app/modules/admin/pages/rooms/components/room-form/room-form.component.ts
- frontend/src/app/modules/admin/pages/rooms/components/room-table/room-table.component.ts
- frontend/src/app/modules/admin/pages/rooms/rooms.component.html
- frontend/src/app/modules/admin/pages/rooms/rooms.component.ts
- frontend/src/app/shared/interfaces/room.ts
- frontend/src/app/shared/services/room.service.ts
> HU19/registro de salas VC

- frontend/src/app/modules/admin/pages/rooms/components/room-table/room-table.component.html
- frontend/src/app/modules/admin/pages/rooms/components/room-table/room-table.component.ts
- frontend/src/app/modules/admin/pages/rooms/rooms.component.html
- frontend/src/app/modules/admin/pages/rooms/rooms.component.ts
> hu24 eliminacion de salas VC

- frontend/src/app/modules/admin/pages/movies/components/movie-table/movie-table.component.html
- frontend/src/app/modules/admin/pages/movies/components/movie-table/movie-table.component.ts
- frontend/src/app/modules/admin/pages/movies/movies.component.html
- frontend/src/app/modules/admin/pages/movies/movies.component.ts
Eliminacion de pelicula implementada
> eliminacion de pelicula cc

- frontend/src/app/modules/admin/pages/rooms/components/room-form/room-form.component.ts
- frontend/src/app/modules/admin/pages/rooms/components/room-table/room-table.component.html
- frontend/src/app/modules/admin/pages/rooms/components/room-table/room-table.component.ts
- frontend/src/app/modules/admin/pages/rooms/rooms.component.html
- frontend/src/app/modules/admin/pages/rooms/rooms.component.ts
- frontend/src/app/shared/services/room.service.ts
> hu18 edicion de salas VC

- frontend/src/app/modules/admin/pages/movies/components/movie-form/movie-form.component.html
- frontend/src/app/modules/admin/pages/movies/components/movie-form/movie-form.component.ts
- frontend/src/app/modules/admin/pages/movies/components/movie-table/movie-table.component.html
- frontend/src/app/modules/admin/pages/movies/components/movie-table/movie-table.component.ts
- frontend/src/app/modules/admin/pages/movies/movies.component.html
- frontend/src/app/modules/admin/pages/movies/movies.component.ts
- frontend/src/app/shared/services/movie.service.ts
Edicion de peliculas implementado
> edicion de peliculas implementado cc

- backend/src/libs/multer.js
solucion a subida de archivos a carpeta uploads
> solucion a carpetas de archivos backend cc

- frontend/src/app/shared/components/navbar/navbar.component.html
Navegacion basica implementada
> navegacion basica implementada cc

- frontend/src/app/modules/admin/pages/movies/components/movie-form/movie-form.component.ts
Validaciones en formulario de pelicula agregadas
> validaciones agregadas

- frontend/src/app/app.component.html
- frontend/src/app/app.module.ts
- frontend/src/app/shared/components/navbar/navbar.component.html
- frontend/src/app/shared/components/navbar/navbar.component.ts
- frontend/src/app/shared/primeng.module.ts
migracion de la barra de navegacion con botones y funcionalidad basica
> navbar migrado a primeng cc

- frontend/src/app/modules/management/management.module.ts
- frontend/src/app/modules/management/pages/users/components/user-form/user-form.component.html
- frontend/src/app/modules/management/pages/users/components/user-form/user-form.component.ts
- frontend/src/app/modules/management/pages/users/components/user-table/user-table.component.html
- frontend/src/app/modules/management/pages/users/users.component.html
- frontend/src/app/modules/management/pages/users/users.component.ts
- frontend/src/app/shared/primeng.module.ts
migracion de frontend realizada, creacion de usuario implementada
> hu3, migracion de frontend realizada, creacion de usuario implementada

- frontend/src/app/modules/management/pages/users/components/user-form/user-form.component.html
- frontend/src/app/modules/management/pages/users/components/user-form/user-form.component.ts
- frontend/src/app/modules/management/pages/users/components/user-table/user-table.component.html
- frontend/src/app/modules/management/pages/users/users.component.html
- frontend/src/app/modules/management/pages/users/users.component.ts
- frontend/src/app/shared/interfaces/user.ts
- frontend/src/app/shared/primeng.module.ts
- frontend/src/app/shared/services/user.service.ts
edicion de usuario implementada, mensajes de alerta implementados
> edicion de usuario implementada, mensajes de alerta implementados cc

- frontend/src/app/modules/admin/admin.module.ts
- frontend/src/app/modules/admin/pages/movies/components/movie-form/movie-form.component.html
- frontend/src/app/modules/admin/pages/movies/components/movie-form/movie-form.component.ts
- frontend/src/app/modules/admin/pages/movies/components/movie-table/movie-table.component.html
- frontend/src/app/modules/admin/pages/movies/movies.component.html
- frontend/src/app/modules/admin/pages/movies/movies.component.ts
- frontend/src/app/modules/management/pages/users/components/user-form/user-form.component.html
- frontend/src/app/shared/primeng.module.ts
migracion de interfaz a primeng
> gui migrado a primeng cc

- frontend/src/app/modules/admin/pages/movies/components/movie-form/movie-form.component.html
- frontend/src/app/modules/admin/pages/movies/components/movie-form/movie-form.component.ts
- frontend/src/app/modules/admin/pages/movies/components/movie-table/movie-table.component.html
- frontend/src/app/modules/admin/pages/movies/movies.component.html
- frontend/src/app/modules/admin/pages/movies/movies.component.ts
- frontend/src/app/shared/primeng.module.ts
Implementada la creacion de peliculas
> migracion de creacion de pelicula implementada cc

- frontend/src/app/modules/admin/pages/cinemas/cinemas.component.html
- frontend/src/app/modules/admin/pages/cinemas/cinemas.component.ts
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-form/cinema-form.component.html
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-form/cinema-form.component.ts
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-table/cinema-table.component.html
- frontend/src/app/modules/admin/pages/rooms/rooms.component.html
H14 GUI de cines con primeng VC
> HU14/GUI de Cines VC

- frontend/src/app/modules/admin/pages/movies/components/movie-form/movie-form.component.ts
- frontend/src/app/modules/admin/pages/movies/components/movie-table/movie-table.component.html
- frontend/src/app/modules/admin/pages/movies/movies.component.html
- frontend/src/app/modules/admin/pages/movies/movies.component.ts
- frontend/src/app/shared/services/movie.service.ts
actualizacion de pelicula implementada
> actualizacion de pelicula implementada cc

- frontend/src/app/modules/management/pages/users/components/user-form/user-form.component.html
- frontend/src/app/modules/management/pages/users/components/user-form/user-form.component.ts
label y rol a dropdown de formulario de usuario
> agregado label y codigo a rol de usuario en formulario cc

- frontend/src/app/modules/admin/pages/cinemas/cinemas.component.html
- frontend/src/app/modules/admin/pages/cinemas/cinemas.component.ts
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-form/cinema-form.component.html
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-form/cinema-form.component.ts
- frontend/src/app/modules/admin/pages/rooms/components/room-form/room-form.component.ts
- frontend/src/app/shared/services/cinema.service.ts
HU16 registro de cines (migration) VC
> HU16 registro de cines VC

- frontend/src/app/modules/admin/pages/cinemas/cinemas.component.html
- frontend/src/app/modules/admin/pages/cinemas/cinemas.component.ts
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-table/cinema-table.component.html
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-table/cinema-table.component.ts
- frontend/src/app/modules/admin/pages/rooms/components/room-form/room-form.component.html
HU25 eliminacion de cines migracion VC
> HU25 eliminacion de cines migracion VC

- frontend/src/app/modules/admin/pages/rooms/components/room-table/room-table.component.html
- frontend/src/app/modules/admin/pages/rooms/components/room-table/room-table.component.ts
- frontend/src/app/modules/admin/pages/rooms/rooms.component.html
- frontend/src/app/modules/admin/pages/rooms/rooms.component.ts
HU24 eliminacion de salas migracion VC
> hu24 eliminacion de salas migracion VC

- backend/src/controllers/rooms.controller.js
- backend/src/models/room.js
> eliminacion de sala en cascada implementado en backend cc

- frontend/src/app/modules/admin/pages/cinemas/components/cinema-form/cinema-form.component.html
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-form/cinema-form.component.ts
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-table/cinema-table.component.html
- frontend/src/app/modules/admin/pages/movies/components/movie-form/movie-form.component.html
- frontend/src/app/modules/admin/pages/movies/components/movie-form/movie-form.component.ts
- frontend/src/app/modules/admin/pages/movies/components/movie-table/movie-table.component.html
- frontend/src/app/modules/admin/pages/movies/components/movie-table/movie-table.component.ts
- frontend/src/app/modules/admin/pages/rooms/components/room-form/room-form.component.html
- frontend/src/app/modules/admin/pages/rooms/components/room-form/room-form.component.ts
- frontend/src/app/modules/admin/pages/rooms/components/room-table/room-table.component.html
- frontend/src/app/modules/management/pages/users/components/user-form/user-form.component.html
- frontend/src/app/modules/management/pages/users/components/user-form/user-form.component.ts
- frontend/src/app/modules/management/pages/users/users.component.html
- frontend/src/app/shared/services/movie.service.ts
Fixes menores a problemas en frontend
> fixes menores cc

- .gitignore
- backend/src/controllers/cinemas.controller.js
- backend/src/controllers/movies.controller.js
- backend/src/models/movie.js
> anidacion en creacion de cines con peliculas cc

- backend/src/controllers/cinemas.controller.js
- backend/src/controllers/rooms.controller.js
- backend/src/models/cinema.js
- frontend/src/app/modules/admin/pages/cinemas/cinemas.component.ts
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-form/cinema-form.component.html
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-form/cinema-form.component.ts
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-table/cinema-table.component.html
- frontend/src/app/shared/interfaces/cinema.ts
actualizacion de peliculas en cines
> actualizacion anidada de peliculas en cine cc

- frontend/src/app/modules/management/management-routing.module.ts
- frontend/src/app/modules/management/management.component.ts
- frontend/src/app/modules/management/management.module.ts
- frontend/src/app/modules/management/pages/profile/profile.component.html
- frontend/src/app/modules/management/pages/profile/profile.component.ts
> HU29 GUI perfil de gerente

- backend/src/controllers/cinemas.controller.js
- backend/src/models/cinema.js
- backend/src/routes/cinemas.routes.js
- frontend/src/app/modules/admin/pages/cinemas/cinemas.component.ts
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-form/cinema-form.component.html
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-form/cinema-form.component.ts
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-table/cinema-table.component.html
- frontend/src/app/modules/admin/pages/cinemas/components/cinema-table/cinema-table.component.ts
- frontend/src/app/modules/admin/pages/movies/components/movie-form/movie-form.component.html
- frontend/src/app/shared/interfaces/cinema.ts
- frontend/src/app/shared/services/cinema.service.ts
- frontend/src/app/shared/services/movie.service.ts
refactorizacion completa de cinema
> refactorizacion de funcionamiento de cinema cc

- .gitignore
- backend/src/controllers/rooms.controller.js
- backend/src/models/room.js
- frontend/src/app/modules/admin/pages/cinemas/cinemas.component.ts
- frontend/src/app/modules/admin/pages/rooms/components/room-form/room-form.component.ts
> Room refactor

- backend/src/controllers/cinemas.controller.js
- backend/src/controllers/functions.controller.js
- backend/src/controllers/movies.controller.js
- backend/src/controllers/rooms.controller.js
- backend/src/routes/cinemas.routes.js
- backend/src/routes/functions.routes.js
- backend/src/routes/movies.routes.js
- backend/src/routes/rooms.routes.js
> funciones para consultas anidadas

- frontend/src/app/modules/admin/pages/cinemas/components/cinema-table/cinema-table.component.html
- frontend/src/app/modules/admin/pages/functions/components/function-table/function-table.component.html
- frontend/src/app/modules/admin/pages/movies/components/movie-table/movie-table.component.html
- frontend/src/app/modules/admin/pages/rooms/components/room-table/room-table.component.html
- frontend/src/app/modules/management/pages/users/components/user-table/user-table.component.html
ordenamiento en las tablas crud
> Ordenamiento en tablas crud cc

- backend/src/routes/movies.routes.js
- frontend/angular.json
- frontend/package.json
- frontend/src/app/app.component.ts
- frontend/src/app/modules/auth/pages/login/login.component.html
- frontend/src/app/modules/client/client-routing.module.ts
- frontend/src/app/modules/client/client.module.ts
- frontend/src/app/modules/client/pages/movie/components/movie-property/movie-property.component.html
- frontend/src/app/modules/client/pages/movie/components/movie-property/movie-property.component.ts
- frontend/src/app/modules/client/pages/movie/movie.component.html
- frontend/src/app/modules/client/pages/movie/movie.component.ts
- frontend/src/app/shared/components/navbar/navbar.component.html
- frontend/src/app/shared/components/navbar/navbar.component.ts
- frontend/src/app/shared/components/option-card/option-card.component.html
- frontend/src/app/shared/services/movie.service.ts
gui frontend de movie creado, sin funcionalidad
> frontend gui de movie creado cc

- frontend/src/app/modules/client/client-routing.module.ts
- frontend/src/app/modules/client/client.module.ts
- frontend/src/app/modules/client/pages/theaters/cinema-card/cinema-card.component.html
- frontend/src/app/modules/client/pages/theaters/cinema-card/cinema-card.component.ts
- frontend/src/app/modules/client/pages/theaters/theaters.component.html
- frontend/src/app/modules/client/pages/theaters/theaters.component.ts
> HU12/cines disponibles VC

- backend/src/controllers/cinemas.controller.js
- backend/src/controllers/functions.controller.js
- backend/src/controllers/movies.controller.js
- backend/src/controllers/rooms.controller.js
- frontend/src/app/modules/admin/pages/functions/components/function-form/function-form.component.html
- frontend/src/app/modules/admin/pages/functions/components/function-form/function-form.component.ts
- frontend/src/app/modules/admin/pages/functions/components/function-table/function-table.component.html
- frontend/src/app/modules/admin/pages/functions/components/function-table/function-table.component.ts
- frontend/src/app/modules/admin/pages/functions/functions.component.html
- frontend/src/app/modules/admin/pages/functions/functions.component.ts
creacion de funcion actualizada, eliminacion en cascada implementada, vista de detalles de funcion implementada
> creacion, eliminacion y detalles de funcion cc
